### ISSUE TITLE
Replicating steps outside of VS code

### ISSUE THREAD

**Issue by fhightower** [rpompen/mkproj-demo#1]
Hi 👋   I'm relatively new to clojure(script) and really appreciate this repository as it is very simple. The difficulty is that I'm not using VS code so I'm trying to replicate the instructions outside of VS code.

Do you know how to replicate steps 8 and 9 outside of VS code?

> 8. then start project with `ctrl-alt-c ctrl-alt-j`
> 9. select `Clojure CLI + Figwheel-main`, then `:fig` option in next dialogue

Thanks!

**Comment by rpompen** [comment]
Hello Floyd,

Currently it runs:
clojure -Sdeps '{:deps {nrepl/nrepl
{:mvn/version,"0.8.3"},cider/cider-nrepl
{:mvn/version,"0.26.0"},cider/piggieback {:mvn/version,"0.5.2"}}}' -A:fig
-m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware
cider.piggieback/wrap-cljs-repl]"

I hope it helps!

Thanks for checking out my project.

Regards,

Roel

**Comment by fhightower** [comment]
Perfect, thanks Roel!
